# Generated by Django 2.2.4 on 2019-09-06 13:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190906_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='next_payment',
            field=models.DateField(default=main.models.next_year, verbose_name='Next Payment'),
        ),
        migrations.AddField(
            model_name='profile',
            name='plan',
            field=models.ForeignKey(default=main.models.get_basic_plan, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.PaymentPlan'),
        ),
    ]
