# Generated by Django 2.2.4 on 2019-09-08 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190906_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentplan',
            options={'ordering': ['name_slug']},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['title_slug']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name_slug']},
        ),
        migrations.AddField(
            model_name='profile',
            name='saved_recipes',
            field=models.ManyToManyField(related_name='saved_by', to='main.Recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='title_slug',
            field=models.SlugField(default='', max_length=150, unique=True, verbose_name='Title Slug'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RecipeRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='Rating')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profile')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Recipe')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='rated_recipes',
            field=models.ManyToManyField(related_name='ratings', related_query_name='rating', through='main.RecipeRating', to='main.Recipe'),
        ),
    ]
