# Generated by Django 2.2.4 on 2019-09-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190915_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(through='main.UserTag', to='main.Tag'),
        ),
    ]
