# Generated by Django 2.2.4 on 2019-09-29 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_recipe_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rated_recipes',
        ),
    ]
