# Generated by Django 2.2.4 on 2019-10-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20191001_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(default='', max_length=3, unique=True, verbose_name='Letter')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
            ],
            options={
                'ordering': ['letter'],
            },
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['sort_title']},
        ),
        migrations.AddField(
            model_name='recipe',
            name='first_letter',
            field=models.CharField(default='', max_length=3, verbose_name='First Letter'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='sort_title',
            field=models.CharField(default='', max_length=150, verbose_name='Sort Title'),
        ),
    ]
