# Generated by Django 2.2.4 on 2019-12-16 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20191212_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscription_end',
            field=models.DateField(default=datetime.date(3020, 1, 1), verbose_name='Subscription End'),
            preserve_default=False,
        ),
    ]
