# Generated by Django 2.2.4 on 2019-09-04 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('name_slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('ingredients_text', models.TextField(verbose_name='Ingredients')),
                ('ingredients_html', models.TextField(verbose_name='Ingredients HTML')),
                ('instructions_text', models.TextField(verbose_name='Instructions')),
                ('instructions_html', models.TextField(verbose_name='Instructions HTML')),
                ('tags', models.ManyToManyField(to='main.Tag')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_pay', models.DateField(default=main.models.next_year, verbose_name='Next Payment')),
                ('plan', models.CharField(choices=[('B', 'BASIC'), ('P', 'PREMIUM'), ('A', 'API'), ('C', 'CUSTOM')], default='B', max_length=1, verbose_name='Payment Plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
