# Generated by Django 2.2.4 on 2019-09-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Name')),
                ('name_slug', models.SlugField(max_length=25, unique=True, verbose_name='Name Slug')),
                ('interval', models.PositiveSmallIntegerField(default=365, verbose_name='Days between payments')),
                ('amount', models.PositiveSmallIntegerField(default=10, verbose_name='Amount')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='next_pay',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='plan',
        ),
    ]
