# Generated by Django 3.0.1 on 2020-03-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200318_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='payment_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'FAILED'), (1, 'NEEDS CONFIRMATION'), (2, 'TRIAL'), (3, 'SUCCESS'), (4, 'PENDING'), (5, 'CANCELED')], default=4, verbose_name='Payment Status'),
        ),
    ]
