# Generated by Django 3.0.1 on 2020-03-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200318_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='checkout_session',
            field=models.CharField(default='', max_length=50, verbose_name='Stripe Checkout Session'),
        ),
    ]
