# Generated by Django 3.0.1 on 2020-03-20 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_profile_checkout_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='checkout_session',
            field=models.CharField(default='', max_length=100, verbose_name='Stripe Checkout Session'),
        ),
    ]
