# Generated by Django 3.0.1 on 2020-03-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200320_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscription_status',
            field=models.CharField(choices=[('', 'undefined'), ('admin', 'Administrator'), ('free', 'Free Account'), ('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete, Session Expired'), ('trialing', 'Free Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid')], default='', max_length=25, verbose_name='Subscription Status'),
        ),
    ]
