# Generated by Django 2.2.4 on 2019-10-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_profile_rated_recipes'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reciperating',
            constraint=models.UniqueConstraint(fields=('recipe', 'profile'), name='unique_rating'),
        ),
    ]
