# Generated by Django 2.2.4 on 2019-10-13 01:50

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20191005_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Recipe of the Day'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='last_featured',
            field=models.DateField(default=datetime.date(1970, 1, 1), verbose_name='Last Featured'),
        ),
    ]
