# Generated by Django 2.2.4 on 2019-10-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20191013_0150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reciperating',
            options={'ordering': ['profile', 'recipe__sort_title']},
        ),
        migrations.AlterField(
            model_name='reciperating',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], verbose_name='Rating'),
        ),
    ]
