# Generated by Django 2.2.4 on 2019-11-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20191110_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='payment_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'FAILED'), (1, 'PENDING'), (2, 'TRIAL'), (3, 'SUCCESS')], default=1, verbose_name='Payment Status'),
        ),
    ]
