# Generated by Django 2.2.4 on 2019-12-12 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_profile_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='payment_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'FAILED'), (1, 'NEEDS CONFIRMATION'), (2, 'TRIAL'), (3, 'SUCCESS')], default=1, verbose_name='Payment Status'),
        ),
    ]
