# Generated by Django 3.0.1 on 2020-02-10 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200210_0206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LetterCount',
        ),
        migrations.RemoveField(
            model_name='reciperating',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='reciperating',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='usertag',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='usertag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='usertag',
            name='user',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.DeleteModel(
            name='RecipeRating',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='UserTag',
        ),
    ]
