# Generated by Django 3.0.1 on 2020-02-11 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200210_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_sub',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name='Last Submission'),
        ),
        migrations.AddField(
            model_name='profile',
            name='rate_level',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Rate Level'),
        ),
    ]
