# Generated by Django 3.0.1 on 2020-02-23 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients_text',
            field=models.TextField(help_text='Tip: list ingredients in the order they are used', verbose_name='Ingredients'),
        ),
    ]
