# Generated by Django 3.0.1 on 2020-02-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20200223_0016'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usertag',
            constraint=models.UniqueConstraint(fields=('user', 'tag', 'recipe'), name='unique_user_tag'),
        ),
    ]
