# Generated by Django 3.0.1 on 2020-04-02 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20200224_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='quantity_html',
            field=models.CharField(default='', max_length=400, verbose_name='Quantity HTML'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='quantity_text',
            field=models.CharField(default='', max_length=200, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='see_also',
            field=models.ManyToManyField(related_name='_recipe_see_also_+', to='recipes.Recipe'),
        ),
    ]
