# Generated by Django 3.0.1 on 2020-04-11 02:49

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20200402_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='quantity_text',
            field=models.CharField(default='', max_length=200, verbose_name='Yield'),
        ),
    ]
