# Generated by Django 3.0.1 on 2020-04-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20200411_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Datetime Created'),
        ),
    ]
