# Generated by Django 3.0.1 on 2020-04-25 09:25

from django.db import migrations

import datetime

def set_created_dt(apps, schema_editor):
    Recipe = apps.get_model("recipes", "Recipe")
    for recipe in Recipe.objects.all():
        recipe.created_dt = datetime.datetime(year=recipe.created.year,
                                              month=recipe.created.month,
                                              day=recipe.created.day,
                                              tzinfo=datetime.timezone.utc)
        recipe.save()


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_created_dt'),
    ]

    operations = [
        migrations.RunPython(set_created_dt),
    ]

