# Generated by Django 3.1.12 on 2021-08-22 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recipes.models
import recipes.utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0009_recipe_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipePhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('photo', models.ImageField(max_length=200, upload_to=recipes.models.recipe_photo_path, verbose_name='Photo')),
                ('reviewed', models.BooleanField(default=False, verbose_name='Reviewed')),
                ('approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('resized', models.BooleanField(default=False, verbose_name='Resized options created')),
                ('timestamp', models.DateTimeField(default=recipes.utils.utc_now, editable=False, verbose_name='Timestamp')),
                ('caption', models.CharField(blank=True, default='', max_length=200, verbose_name='Caption')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['recipe__sort_title', '-timestamp'],
            },
        ),
    ]
