# Generated by Django 3.1.13 on 2021-10-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_recipephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='hashtag',
            field=models.BooleanField(default=False, verbose_name='Use as hashtag'),
        ),
    ]
