# Generated by Django 4.0.3 on 2022-03-13 02:55

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_tag_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=recipes.models.tag_photo_path, verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='see_also',
            field=models.ManyToManyField(blank=True, to='recipes.recipe'),
        ),
    ]
