# Generated by Django 5.2.17 on 2026-08-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0012_tag_photo_alter_recipe_see_also"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipephoto",
            name="order",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="Order"),
        ),
    ]
